# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: customer_service.proto for package 'proto'

require 'grpc'
require 'customer_service_pb'

module Proto
  module CustomerService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.CustomerService'

      rpc :ListPerson, RequestType, stream(Person)
      rpc :AddPerson, Person, ResponseType
    end

    Stub = Service.rpc_stub_class
  end
end
